[package]
name = "lolcate-rs"
version = "0.1.3"
description = "A comically fast way of indexing and querying your filesystem. Replaces locate / mlocate / updatedb."
documentation = "https://github.com/ngirard/lolcate-rs/blob/master/README.md"
readme = "README.md"
repository = "https://github.com/ngirard/lolcate-rs"
keywords = ["filesystem-indexer", "search", "regex"]
categories = ["command-line-utilities", "filesystem"]
license = "GPL-3.0"
authors = ["Nicolas Girard <girard.nicolas@gmail.com>"]
edition = "2018"
exclude = [
    "/misc/**",
    "/mk_test_tree.sh",
    "notes.txt",
    "/test/**"
]

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.43"
atty = "0.2.14"
bstr = "0.2"
clap = "2"
colored = { git = "https://github.com/wojciechkepka/colored", branch = "master", features = ["serde"] }
crossbeam-channel = "0.5"
dirs = "3.0"
file_type_enum = "0.11.1"
ignore = "0.4"
lscolors = "0.7.1"
lz4 = "1"
num_cpus = "1.13.0"
once_cell = "1.8.0"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.28"
toml = "0.5"
walkdir = "2"

[target.'cfg(not(windows))'.dependencies]
expanduser = "1.2"

[[bin]]
path = "src/main.rs"
name = "lolcate"

[profile.release]
lto = true
